# Generated by bower2nix v3.3.1 (https://github.com/rvl/bower2nix)
{ fetchbower, buildEnv }:
buildEnv { name = "bower-env"; ignoreCollisions = true; paths = [
  (fetchbower "jquery" "3.6.1" "^3" "16r46i8ppmgkag9smj6aq7bnny8fxkgzxd7gbms0gcqd1hw4wlck")
  (fetchbower "bootstrap" "3.4.1" "^3.3.7" "05r6w4vbs9sqmicbjbadjd0qg3vzpz8snvnk2l3c91k3k1qwxjih")
  (fetchbower "moment" "2.29.4" "^2.10" "0yry869qxfk98qlmnxl41817r7lqhx5bbylwmmgdgh06px5chmqi")
  (fetchbower "gettext.js" "0.7.0" "^0.7" "1y07j3qhd0pjlp4bzi75gcj26iqgfw7xf5sjf8h3ipwr3mhiqll7")
  (fetchbower "c3" "0.7.20" "^0.7" "1zy4297qf2qckfdczcp16bn28ly8n3bbv42pax9cwbnsifrhb85j")
  (fetchbower "papaparse" "5.3.2" "^5.0" "1gxnh7mscd6m0drjq99d5vpvpi78qjfx73d82d773sxlvqdvfm32")
  (fetchbower "fullcalendar" "3.10.5" "^3.10.2" "02mkri3qqqj9xlh471vz9qdnv2dybvmjjd5073da0brcvkd5lbwg")
  (fetchbower "mousetrap" "1.6.5" "^1.6" "071cpvm8lnq0y49fhww4w8ywrazs1jiy072vpvxfzcp10091aw60")
  (fetchbower "bootstrap-rtl-ondemand" "3.3.4-ondemand" "^3.3.4-ondemand" "0j2c5m3icskql0648cq71wgf6iixbl4p8kqva7v4phcc42qrml4g")
  (fetchbower "Sortable" "sortablejs#1.15.0" "sortablejs#^1.8.4" "074qwfa78v86g253skbr4qw2sh393svc63vrsn8m9w4v4j50l2ka")
  (fetchbower "qunit" "1.23.1" "^1.18" "0gif1wmdw2hiz1y30xvycwa6fx78ik2wc8dqqzh0yk923y54xdz6")
  (fetchbower "d3" "5.16.0" "^5.0.0" "0x1wkxhi3iypaldix1g8p4dz38lfqkd4dlbgfw5dv8h8bqx7wjxf")
]; }
